# Reference: https://andrewdolby.com/articles/2016/continuous-deployment-for-qt-applications/

os: osx

language: cpp

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8

install:
  - brew update
  - brew reinstall cgal
  - brew reinstall qt5
  - wget -O installrust.sh https://sh.rustup.rs
  - sh installrust.sh -y
  - export PATH="$HOME/.cargo/bin:/usr/local/opt/qt/bin:$(brew --prefix)/bin:$PATH"

script:
  - git clone https://github.com/huxingyi/meshlite.git
  - cd meshlite
  - cargo build --release
  - cd ../
  - cp meshlite/include/meshlite.h thirdparty/meshlite/meshlite.h
  - cp meshlite/target/release/libmeshlite.dylib thirdparty/meshlite/libmeshlite.dylib
  - qmake -config release
  - make
  - mv dust3d.app dust3d_unstable.app
  - macdeployqt dust3d_unstable.app -dmg
  - sh ci/upload-github-release-asset.sh github_api_token=${my_auth_token} branch=$TRAVIS_BRANCH owner=huxingyi repo=dust3d tag=unstable filename=dust3d_unstable.dmg
